// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Tools;
//
//    var external = External.FromJson(jsonString);

namespace Tools
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class External
    {
        [JsonProperty("ip")]
        public string Ip { get; set; }
    }

    public partial class External
    {
        public static External FromJson(string json) => JsonConvert.DeserializeObject<External>(json, Tools.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this External self) => JsonConvert.SerializeObject(self, Tools.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
